name: Deploy AWS Lambda

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Adjust to your desired region

    
    - name: Zip the Lambda function
      run: |
        zip -r function.zip .  # Include all necessary files

    - name: Deploy Lambda function
      run: |
        aws lambda update-function-code \
          --function-name myapi \
          --zip-file fileb://function.zip

    - name: Invalidate API Gateway cache (optional)
      run: |
        aws apigateway invalidate-cache \
          --rest-api-id myapi \
          --stage-name dev
